### PR TITLE
Fix Crate Keys not working on NexEngine 2.2.7

### PR DESCRIPTION
**Pull request by Oribuin**
Fixes the NoSuchMethodError shown when using ExcellentCrates v4.0.6 and NexEngine 2.2.7

This problem is mentioned on issue #64
Error:
```
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack su.nexmedia.engine.api.config.JYML.getItem(java.lang.String, java.lang.String)'
        at su.nightexpress.excellentcrates.key.CrateKey.<init>(CrateKey.java:51) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nightexpress.excellentcrates.key.KeyManager.onLoad(KeyManager.java:50) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.ExcellentCrates.enable(ExcellentCrates.java:63) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:212) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.reload(NexPlugin.java:98) ~[NexEngine.jar:?]
        at su.nexmedia.engine.command.list.ReloadSubCommand.onExecute(ReloadSubCommand.java:39) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.command.AbstractCommand.execute(AbstractCommand.java:181) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.command.GeneralCommand.onCommand(GeneralCommand.java:102) ~[NexEngine.jar:?]
        at su.nexmedia.engine.command.CommandRegister.execute(CommandRegister.java:121) ~[NexEngine.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

### CODE REVIEW

**Comment by nulli0n** [comment]
Not needed anymore.
